// Theme configuration for the home page
// Change the primary color here to update the entire home page theme

export const theme = {
  // Main brand color - change this to update the entire theme
  // Options: "green", "blue", "purple", "orange", "red", "pink", "indigo", "teal", "cyan"
  primary: "indigo",
} as const;

// Color mappings for Tailwind classes
export const colors = {
  green: {
    text: "text-green-600",
    textHover: "hover:text-green-600",
    bg: "bg-green-600",
    bgHover: "hover:bg-green-700",
    bgLight: "bg-green-400/10",
    bgGradient: "from-green-500 to-green-600",
    footerGradient: "from-white via-green-200/60 to-white",
    border: "border-green-300",
    stroke: "stroke-green-600",
    fill: "fill-green-500",
    ring: "ring-green-500",
    svgStroke: "#00C34D",
  },
  blue: {
    text: "text-blue-600",
    textHover: "hover:text-blue-600",
    bg: "bg-blue-600",
    bgHover: "hover:bg-blue-700",
    bgLight: "bg-blue-400/10",
    bgGradient: "from-blue-500 to-blue-600",
    footerGradient: "from-white via-blue-200/60 to-white",
    border: "border-blue-300",
    stroke: "stroke-blue-600",
    fill: "fill-blue-500",
    ring: "ring-blue-500",
    svgStroke: "#2563EB",
  },
  purple: {
    text: "text-purple-600",
    textHover: "hover:text-purple-600",
    bg: "bg-purple-600",
    bgHover: "hover:bg-purple-700",
    bgLight: "bg-purple-400/10",
    bgGradient: "from-purple-500 to-purple-600",
    footerGradient: "from-white via-purple-200/60 to-white",
    border: "border-purple-300",
    stroke: "stroke-purple-600",
    fill: "fill-purple-500",
    ring: "ring-purple-500",
    svgStroke: "#9333EA",
  },
  orange: {
    text: "text-orange-600",
    textHover: "hover:text-orange-600",
    bg: "bg-orange-600",
    bgHover: "hover:bg-orange-700",
    bgLight: "bg-orange-400/10",
    bgGradient: "from-orange-500 to-orange-600",
    footerGradient: "from-white via-orange-200/60 to-white",
    border: "border-orange-300",
    stroke: "stroke-orange-600",
    fill: "fill-orange-500",
    ring: "ring-orange-500",
    svgStroke: "#EA580C",
  },
  red: {
    text: "text-red-600",
    textHover: "hover:text-red-600",
    bg: "bg-red-600",
    bgHover: "hover:bg-red-700",
    bgLight: "bg-red-400/10",
    bgGradient: "from-red-500 to-red-600",
    footerGradient: "from-white via-red-200/60 to-white",
    border: "border-red-300",
    stroke: "stroke-red-600",
    fill: "fill-red-500",
    ring: "ring-red-500",
    svgStroke: "#DC2626",
  },
  pink: {
    text: "text-pink-600",
    textHover: "hover:text-pink-600",
    bg: "bg-pink-600",
    bgHover: "hover:bg-pink-700",
    bgLight: "bg-pink-400/10",
    bgGradient: "from-pink-500 to-pink-600",
    footerGradient: "from-white via-pink-200/60 to-white",
    border: "border-pink-300",
    stroke: "stroke-pink-600",
    fill: "fill-pink-500",
    ring: "ring-pink-500",
    svgStroke: "#DB2777",
  },
  indigo: {
    text: "text-indigo-600",
    textHover: "hover:text-indigo-600",
    bg: "bg-indigo-600",
    bgHover: "hover:bg-indigo-700",
    bgLight: "bg-indigo-400/10",
    bgGradient: "from-indigo-500 to-indigo-600",
    footerGradient: "from-white via-indigo-200/60 to-white",
    border: "border-indigo-300",
    stroke: "stroke-indigo-600",
    fill: "fill-indigo-500",
    ring: "ring-indigo-500",
    svgStroke: "#4F46E5",
  },
  teal: {
    text: "text-teal-600",
    textHover: "hover:text-teal-600",
    bg: "bg-teal-600",
    bgHover: "hover:bg-teal-700",
    bgLight: "bg-teal-400/10",
    bgGradient: "from-teal-500 to-teal-600",
    footerGradient: "from-white via-teal-200/60 to-white",
    border: "border-teal-300",
    stroke: "stroke-teal-600",
    fill: "fill-teal-500",
    ring: "ring-teal-500",
    svgStroke: "#0D9488",
  },
  cyan: {
    text: "text-cyan-600",
    textHover: "hover:text-cyan-600",
    bg: "bg-cyan-600",
    bgHover: "hover:bg-cyan-700",
    bgLight: "bg-cyan-400/10",
    bgGradient: "from-cyan-500 to-cyan-600",
    footerGradient: "from-white via-cyan-200/60 to-white",
    border: "border-cyan-300",
    stroke: "stroke-cyan-600",
    fill: "fill-cyan-500",
    ring: "ring-cyan-500",
    svgStroke: "#0891B2",
  },
} as const;

// Get current theme colors
export const getThemeColors = () => colors[theme.primary];

// Export for convenience
export type ThemeColor = keyof typeof colors;
